### ISSUE TITLE
OSX M1 installation issue

### ISSUE THREAD

**Issue by tartarini** [dafne-imaging/dafne#4]
on OSX Ventura 13.0.1 there is this error in attempting to install dafne in python3.9 and python3.8 environment;

```
pip install dafne
Collecting dafne
  Using cached dafne-1.3a0-py3-none-any.whl (124 kB)
Collecting numpy
  Using cached numpy-1.23.5-cp39-cp39-macosx_11_0_arm64.whl (13.4 MB)
Collecting pyqt5
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/tartarini/DEVELOP/RSE/TRISTAN/pyvenv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/tartarini/DEVELOP/RSE/TRISTAN/pyvenv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/tartarini/DEVELOP/RSE/TRISTAN/pyvenv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/tartarini/DEVELOP/RSE/TRISTAN/pyvenv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/zd/5bq81nyn0gz4ck55yt6nbfnm0000gn/T/pip-build-env-ui0gmpgx/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/zd/5bq81nyn0gz4ck55yt6nbfnm0000gn/T/pip-build-env-ui0gmpgx/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/zd/5bq81nyn0gz4ck55yt6nbfnm0000gn/T/pip-build-env-ui0gmpgx/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 69, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/zd/5bq81nyn0gz4ck55yt6nbfnm0000gn/T/pip-build-env-ui0gmpgx/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/zd/5bq81nyn0gz4ck55yt6nbfnm0000gn/T/pip-build-env-ui0gmpgx/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/zd/5bq81nyn0gz4ck55yt6nbfnm0000gn/T/pip-build-env-ui0gmpgx/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tartarini** [comment]
it seems the pyqt5 doesn't support M1. swapping with pyqt6 in requirements.txt solve the installation
